services:
  app:
    build: .
    container_name: salon_app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: salon_db
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    ports:
      - "5432:5432"
    volumes:
      - salon_db_data:/var/lib/postgresql/data
    secrets:
      - db_password
      - db_user
      - db_name
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U salon_user -d salon_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  salon_db_data:


secrets:
  db_password:
    file: ./creds/db_password.txt
  db_user:
    file: ./creds/db_user.txt
  db_name:
    file: ./creds/db_name.txt
